### PR TITLE
[Tech debt] Font removal per DMCA

### PR DESCRIPTION
**Pull request by kcw-grunt**
## Problem
The original fork of the code used a font without rights and though it was not being used, it should be removed from the codebase

## Definition of Done
- [x] Removed  font files
- [x] Removed references to the old fonts in the codebase

### CODE REVIEW

**Comment by losh11** [comment]
The DMCA AFAIK requires removal of the font from the master branch.

**Comment by mosadialiou** [comment]
Yeah I get it but after the DMCA removal we have to generate a new build and publish on App Store. The changes concerns the codebase.
Also actually `master` doesn't match with the current iOS version but instead the build is from `develop`

**Comment by kcw-grunt** [comment]
thanks @mosadialiou  and @losh11 ...

**Comment by mosadialiou** [comment]
@kcw-grunt It's just a suggestion. So do as you wish.
Normally you should have forked `tech-debt/font-removal` from `develop`. Actually it seems like you did it from `master`.
There is nothing blocking but ...

Thanks for pointing your PR to `develop`

**Pull request merged**
