### PR TITLE
Added integration with ChangeNOW 

### PR DESCRIPTION
**Pull request by ChangeNOW-lab**

### CODE REVIEW

**Comment by kcw-grunt** [comment]
@ChangeNOW-lab  👀   (looking Thanks)

**Review by mosadialiou — DISMISSED** [review]
LGTM

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
Still has the 'Trust Wallet Reference'

Screen Shot 2020-10-28 at 10 04 24 AM


Please remove

**Comment by kcw-grunt** [comment]
cc: @ChangeNOW-lab , @ProninPS

**Comment by kcw-grunt** [comment]
@ProninPS and @ChangeNOW-lab  will you folks also pull in the latest and fix conflicts on the `develop` branch?

**Comment by kcw-grunt** [comment]
Let's this in place of a branch that I'm can submit.

**Pull request closed without merging**
