### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by kcw-grunt**
Set up Bug and Feature Request Issue templates.

### CODE REVIEW

**Comment by mosadialiou** [comment]
Very nice @kcw-grunt
LGTM. Just one thing, let's first merge this branch into develop.

**Review by mosadialiou — CHANGES_REQUESTED** [review]
Very nice @kcw-grunt
LGTM. Just one thing, let's first merge this branch into develop.

**Comment by kcw-grunt** [comment]
Switched to develop @mosadialiou

**Review by mosadialiou — CHANGES_REQUESTED** [review]
Why all these changes? did you create the `kcw-grunt-patch-2` from `develop`? OR maybe `develop` doesn't not yet have the latest code?

**Comment by kcw-grunt** [comment]
maybe the master changes were not brought in...gimme a sec @mosadialiou

**Comment by kcw-grunt** [comment]
Please take a look at https://github.com/litecoin-foundation/loafwallet-ios/pull/121 first @mosadialiou

**Comment by kcw-grunt** [comment]
Will close this until the #121 is merged.  Then I will re-open this

**Pull request closed without merging**
