### PR TITLE
[Tech Debt] Remove recent LTC Price

### PR DESCRIPTION
**Pull request by kcw-grunt**
## Issue
There have been a few customer support tickets where users mistake the recent price with their balance.  This is a serious issue.

## Rationale for the change
Since we have an increasing number of users and we cannot burden them we need to remove any doubt. Especially with the new users of Litewallet

**Pros of removal**: 
- Android doesn't have the price change label
- No confusion
- The fix is trivial (0.5 points)

**Cons of removal**:
- It's purty

## Commits
- adjusted labels and removed price

## Screenshots
Before | After
-------|------
with-price|no-price

### CODE REVIEW

**Comment by mosadialiou** [comment]
@kcw-grunt Sorry to weigh in only now. Personally I really like the recent LTC price. Why can't we just add `per LTC` flag so we will show up this `$138.24 per LTC`?

**Comment by kcw-grunt** [comment]
Maybe adding an animation is better @zenithquinn @mosadialiou @gneo54 ?

**Comment by mosadialiou** [comment]
> Maybe adding an animation is better @zenithquinn @mosadialiou @gneo54 ?
> Adding a pulsing animations (fade in out alpha / 5 secs) of the price will get the point across and make sure people understand , without having to read. Thoughts?

I like this idea. Better than removing it.
Also we have to add the flag `per LTC` to make it clear. It's not a big issue on Android. It will just take 1hour at most to add the flag

**Comment by kcw-grunt** [comment]
Will create a new issue for `just the QR image` and no segmented control

**Pull request closed without merging**
